FROM ghcr.io/acsone/odoo-bedrock:14.0-py39-latest

RUN set -e \
  && apt update \
  && apt -y install --no-install-recommends postgresql-client libpq-dev  git \
  && apt -y clean \
  && rm -rf /var/lib/apt/lists/*

COPY ./entrypoint-db /odoo/start-entrypoint.d/

COPY ./requirements-14.txt /tmp/requirements.txt

RUN pip install setuptools-scm
RUN pip install -r /tmp/requirements.txt

